global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
  - job_name: 'user-management'
    static_configs:
      - targets: ['user-management:4000']
  - job_name: 'data-storage'
    static_configs:
      - targets: ['data-storage:5000']